# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE when there is a push to the main branch.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Create and configure a Workload Identity Provider for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Change the values for the GAR_LOCATION, GKE_ZONE, GKE_CLUSTER, IMAGE, REPOSITORY and DEPLOYMENT_NAME environment variables (below).
#
# For more support on how to run the workflow, please visit https://github.com/google-github-actions/setup-gcloud/tree/master/example-workflows/gke-kustomize

name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/93898855020/locations/global/workloadIdentityPools/forgithubactionid/providers/githubid'
        service_account: 'compute-engine-for-github@github-for-personal-build.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    # - id: 'get_project'
    #   name: 'Use gcloud CLI'
    #   run: echo "##[set-output name=project_name;]gcloud config get project"
    
    - name: 'configure-docker for gcp'
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: 'docker tag'
      run: docker build . --file Dockerfile --tag asia-northeast1-docker.pkg.dev/${GCP_PROJECT}/busybox
      
    - name: 'docker deploy to gcr'
      run: docker push asia-northeast1-docker.pkg.dev/${GCP_PROJECT}/busybox
      # run: docker push gcr.io/${GCP_PROJECT}/busybox
